version: 2.1

jobs:
  avsait:
    docker:
      - image: silex/emacs:27.2
    working_directory: ~/avsait
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y git openssh-client
      - checkout
      - run:
          name: Umgebung
          command: |
            IFLOCAL=1
            echo "Gebe Umgebung aus"
            ls -lart
      - run: git clone https://github.com/haskell/haskell-mode.git
      - run: cd haskell-mode && make
      - run: |
          # install haskell-mode
          cp -r haskell-mode /home/circleci/.emacs.d/
          echo "(add-to-list 'load-path \"/home/circleci/.emacs.d/haskell-mode\")" >> /home/circleci/.emacs
          echo "(require 'haskell-mode)" >> /home/circleci/.emacs
      - run: |
          # test haskell-mode
          emacs --batch --eval "(haskell-mode)"
      - run:
          name: ERT tests
          command: |
            emacs -Q --batch \
              --eval "(setq avsait-debug-p nil)" \
              --eval "(message (emacs-version))" \
              --eval "(message (getenv \"PWD\"))" \
              --eval "(add-to-list 'load-path (getenv \"PWD\"))" \
              --eval "(load \"~/avsait/avsait.el\")" \
              --eval "(load \"~/avsait/avsait-setup-ert-tests.el\")" \
              --eval "(load \"~/avsait/test/avsait-ert-pretty-print-tests.el\")" \
              --eval "(sit-for 1)" \
              -f ert-run-tests-batch-and-exit

workflows:
  avsait-workflow:
    jobs:
      - avsait  
