version: 2.1

jobs:
  avsait:
    docker:
      - image: silex/emacs:27.2
    working_directory: ~/avsait
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y git openssh-client
      - checkout
      - run:
          name: Umgebung
          command: |
            echo "Gebe Umgebung aus"
            ls -lart
      - run:
          name: ERT tests
          command: |
            emacs -Q --batch \
              --eval "(setq avsait-debug-p nil)" \
              --eval "(message (emacs-version))" \
              --eval "(message (getenv \"PWD\"))" \
              --eval "(add-to-list 'load-path (getenv \"PWD\"))" \
              --eval "(load \"~/avsait/avsait-setup-ert-tests.el\")" \
              --eval "(load \"~/avsait/avsait-ert-pretty-print-tests.el\")" \
              --eval "(sit-for 1)" \
              -f ert-run-tests-batch-and-exit

workflows:
  avsait-workflow:
    jobs:
      - avsait  
